apiVersion: v1
kind: Config
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --oidc-issuer-url=https://server.dex.svc.cluster.local:30443/dex
      - --oidc-client-id=YOUR_CLIENT_ID
      - --oidc-client-secret=YOUR_CLIENT_SECRET
      - --oidc-extra-scope=email
      - --certificate-authority=testdata/ca.crt
      - --token-cache-dir=testdata/token-cache
      - --listen-address=127.0.0.1:8000
      - --skip-open-browser
      - -v1
      command: ../kubelogin
